describe('Logowanie', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.pause()
    cy.get(':nth-child(1) > .form-control').type('jkowalski@example.com')
    cy.get(':nth-child(2) > .form-control').type('JanKowalski!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
  })
  it('fails', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.pause()
    cy.get(':nth-child(1) > .form-control').type('jankowalski@example.com')
    cy.get(':nth-child(2) > .form-control').type('JanKowalski!12')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
  })
})

describe('Wizyta', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('jkowalski@example.com')
    cy.get(':nth-child(2) > .form-control').type('JanKowalski!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.pause()
    cy.get(':nth-child(1) > .DoctorInfo_container__ED0-F > a > .btnRound', { timeout: 10000 }).click({force: true})
    cy.pause()
    cy.get(':nth-child(25) > abbr').click({force: true})
    cy.get(':nth-child(7) > .AppointmentForm_slot__J9QQo').click({force: true})
    cy.pause()
    cy.get('.btnSquare').click({force: true})
    cy.get(':nth-child(3) > .d-flex > .btn').click()
    cy.get(':nth-child(3) > :nth-child(2) > .form-control').type("Złamana noga")
    cy.pause()
    cy.get('[type="submit"]').click({force: true})
  })
})
describe('Wizyty_lekarz', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('fgrot@healthycare.pl')
    cy.get(':nth-child(2) > .form-control').type('FranciszekGrot!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.get(':nth-child(10) > abbr', { timeout: 10000 }).click({force: true})
    cy.pause()
    cy.get(':nth-child(1) > :nth-child(6) > .svgLink > svg > path').click({force: true})
  })
})
describe('Odwołanie wizyty', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('jkowalski@example.com')
    cy.get(':nth-child(2) > .form-control').type('JanKowalski!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.pause()
    cy.get('[href="/nadchodzace-wizyty"] > .btnSimple').click()
    cy.pause()
    cy.get(':nth-child(3) > :nth-child(6) > .svgLink > svg > path').click({force: true})
    cy.pause()
    cy.get('.btnSquare').click({force: true})
    cy.get('.btn-danger').click()
  })
})
describe('Potwierdzenie_wizyty', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('aszpak@healthycare.pl')
    cy.get(':nth-child(2) > .form-control').type('AgnieszkaSzpak!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.pause()
    cy.contains('Wizyty').click({force: true})
    cy.pause()
    cy.contains('Zgłoszone wizyty').click({force: true})
    cy.pause()
    cy.get('[href="/wizyty/78"] > svg > path').click({force: true})
    cy.pause()
    cy.get('.bg-blue').click({force: true})
    cy.get('.btn-success')
  })
})
describe('Przypomnienie_hasła', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.pause()
    cy.get('.Auth_btnGroup__LgmER > .Auth_link__GQoIc').click()
    cy.get('#form > .form-group > .form-control').type('')
    cy.pause()
    cy.get('.btnGroup > .bg-blue').click()
  })
})
describe('Zalecenia_pacjent', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('jkowalski@example.com')
    cy.get(':nth-child(2) > .form-control').type('JanKowalski!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.pause()
    cy.get('[href="/wizyty"] > .btnSimple').click({force: true})
    cy.pause()
    cy.get(':nth-child(1) > :nth-child(6) > .svgLink > svg > path').click({force: true})
    cy.contains('Zalecenia i recepty').click({force: true})
  })
})
describe('Recepta_lekarz', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('fgrot@healthycare.pl')
    cy.get(':nth-child(2) > .form-control').type('FranciszekGrot!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.pause()
    cy.get('[href="/wizyty"] > .btnSimple').click()
    cy.pause()
    cy.get(':nth-child(1) > :nth-child(6) > .svgLink > svg > path').click({force: true})
    cy.pause()
    cy.contains('Zalecenia i recepty').click({force: true})
    cy.pause()
    cy.get('.d-grid > .btn').click({force: true})
    cy.get('.formGroup > .d-flex > .btn').click({force: true})
    cy.get('.formGroup > :nth-child(2) > .form-control').type('Rutinoscorbin 100mg')
    cy.contains('Przepisz receptę').click({force: true})
  })
})
describe('Statystyki', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('aszpak@healthycare.pl')
    cy.get(':nth-child(2) > .form-control').type('AgnieszkaSzpak!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.pause()
    cy.get('[href="/statystyki"] > .btnSimple').click({force: true})
    cy.get('.timesContainer > :nth-child(3)').click({force: true})
    cy.get('[name="start_date"]').type('2023-06-01')
    cy.get('[name="end_date"]').type('2023-06-30')
  })
})
describe('Edycja_profilu', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('jkowalski@example.com')
    cy.get(':nth-child(2) > .form-control').type('JanKowalski!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.contains('Jan Kowalski').click({force: true})
    cy.pause()
    cy.get('[href="/profil"]').click({force: true})
    cy.pause()
    cy.get(':nth-child(1) > :nth-child(1) > .btn').click({force: true})
    cy.get(':nth-child(1) > :nth-child(4) > .form-control').type('Acodin')
    cy.get(':nth-child(2) > :nth-child(1) > .btn').click({force: true})
    cy.get(':nth-child(2) > :nth-child(4) > .form-control').type('Soja')
    cy.pause()
    cy.get('.btnSquare').click({force: true})
  })
})
describe('Rejestracja_recepcja', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/logowanie"] > .btnSquare').click()
    cy.get(':nth-child(1) > .form-control').type('aszpak@healthycare.pl')
    cy.get(':nth-child(2) > .form-control').type('AgnieszkaSzpak!1')
    cy.get('.Auth_btnGroup__LgmER > .btnSquare').click({force: true})
    cy.pause()
    cy.contains('Pacjenci').click({force: true})
    cy.get('[href="/rejestracja-pacjenta"]').click({force: true})
    cy.pause()
    cy.get('.twoColumnGrid > :nth-child(1) > .form-group > .form-control').type('Adrian', {force: true})
    cy.get('.twoColumnGrid > :nth-child(2) > .form-group > .form-control').type('Nowak', {force: true})
    cy.get('.twoColumnGrid > :nth-child(3) > .form-group > .form-control').type('01280993578', {force: true})
    cy.get(':nth-child(5) > .form-group > .form-control').type('wijat42259@rockdian.com', {force: true})
    cy.get(':nth-child(6) > .form-group > .form-control').type('+48503457903', {force: true})
    cy.get('.UserPanel_addressArea__yaAy- > :nth-child(2) > .form-group > .form-control').type('Kwiatowa 2', {force: true})    
    cy.get('.UserPanel_addressArea__yaAy- > :nth-child(3) > .form-group > .form-control').type('10-693', {force: true})
    cy.get('.UserPanel_addressArea__yaAy- > :nth-child(4) > .form-group > .form-control').type('Olsztyn', {force: true})
    cy.get('.btnSquare').click({force: true})
  })
})
describe('Rejestracja_pacjent', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[href="/rejestracja"] > .btnSquare').click({force: true})
    cy.get(':nth-child(1) > .form-control').type('hehe')
    cy.get(':nth-child(2) > .form-control').type('Haslo12!')
    cy.get(':nth-child(3) > .form-control').type('Haslo12!')
    cy.contains('Zarejestruj').click({force: true})
  })
})