# Generated by Django 4.1.7 on 2023-04-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Oczekuje na weryfikację', 'Oczekuje na weryfikację'), ('Zweryfikowana', 'Zweryfikowana'), ('Odbyta', 'Odbyta'), ('Anulowana', 'Anulowana')], max_length=50, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=10, verbose_name='Godzina')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Objawy')),
                ('medicine', models.TextField(blank=True, null=True, verbose_name='Stosowane leki')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Zalecenia')),
            ],
            options={
                'verbose_name': 'Wizyta',
                'verbose_name_plural': 'Wizyty',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=4, verbose_name='Kod dostępu')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wystawienia')),
                ('medicine', models.TextField(verbose_name='Leki')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.appointment', verbose_name='Wizyta')),
            ],
            options={
                'verbose_name': 'Recepta',
                'verbose_name_plural': 'Recepty',
                'ordering': ['id'],
            },
        ),
    ]
