# Generated by Django 4.1.7 on 2023-04-29 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='added_at',
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Wystawiono'),
            preserve_default=False,
        ),
    ]
