# Generated by Django 4.1.7 on 2023-05-05 21:31

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_schedule_end_date'),
        ('appointments', '0004_remove_prescription_added_at_prescription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dawkowanie'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='employees.doctor', verbose_name='Lekarz'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='medicine',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Stosowane leki'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Oczekuje na potwierdzenie', 'Oczekuje na potwierdzenie'), ('Potwierdzona', 'Potwierdzona'), ('Odbyta', 'Odbyta'), ('Anulowana', 'Anulowana')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Objawy'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), size=None, verbose_name='Leki'),
        ),
    ]
