# Generated by Django 4.1.7 on 2023-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='access_code',
            field=models.CharField(max_length=8, verbose_name='Kod dostępu'),
        ),
    ]
