# Generated by Django 4.1.7 on 2023-05-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Oczekuje na potwierdzenie', 'Oczekuje na potwierdzenie'), ('Potwierdzona', 'Potwierdzona'), ('Odbyta', 'Odbyta'), ('Anulowana', 'Anulowana')], default='Oczekuje na potwierdzenie', max_length=50, verbose_name='Status'),
        ),
    ]
