# Generated by Django 4.1.7 on 2023-06-05 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_prescription_expires_at_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='control_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Wizyta kontrolna'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 23, 9, 44, 797221, tzinfo=datetime.timezone.utc), verbose_name='Wygasa'),
        ),
    ]
