# Generated by Django 4.1.7 on 2023-06-05 23:14

import apps.appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_appointment_control_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='expires_at',
            field=models.DateTimeField(default=apps.appointments.models.thirty_days_from_now, verbose_name='Wygasa'),
        ),
    ]
