# Generated by Django 4.1.7 on 2023-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail (login)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Pacjent', 'Pacjent'), ('Lekarz', 'Lekarz'), ('Recepcjonista', 'Recepcjonista'), ('Admin', 'Admin')], default='Pacjent', max_length=50, verbose_name='Rodzaj'),
        ),
    ]
