# Generated by Django 4.1.7 on 2023-05-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('Nowy user', 'Nowy user'), ('Pacjent', 'Pacjent'), ('Lekarz', 'Lekarz'), ('Recepcjonista', 'Recepcjonista'), ('Admin', 'Admin')], default='Nowy user', max_length=50, null=True, verbose_name='Rodzaj'),
        ),
    ]
