# Generated by Django 4.1.7 on 2023-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('Nowy użytkownik', 'Nowy użytkownik'), ('Pacjent', 'Pacjent'), ('Lekarz', 'Lekarz'), ('Recepcjonista', 'Recepcjonista'), ('Admin', 'Admin')], default='Nowy użytkownik', max_length=50, verbose_name='Rodzaj'),
        ),
    ]
