# Generated by Django 4.1.7 on 2023-04-29 19:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('pesel', models.CharField(max_length=11, unique=True, verbose_name='PESEL')),
                ('birthdate', models.DateField(verbose_name='Data urodzenia')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adres e-mail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numer telefonu')),
                ('street', models.CharField(max_length=100, verbose_name='Ulica')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miejscowość')),
                ('medicine', models.TextField(blank=True, null=True, verbose_name='Przyjmowane leki')),
                ('alergies', models.TextField(blank=True, null=True, verbose_name='Alergie')),
                ('diseases', models.TextField(blank=True, null=True, verbose_name='Choroby')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Pacjent',
                'verbose_name_plural': 'Pacjenci',
                'ordering': ['id'],
            },
        ),
    ]
