# Generated by Django 4.1.7 on 2023-05-05 21:31

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='alergies',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Alergie'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diseases',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Choroby'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medicine',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Przyjmowane leki'),
        ),
    ]
