# Generated by Django 4.1.7 on 2023-05-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_alergies_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patients', verbose_name='Zdjęcie'),
        ),
    ]
