# Generated by Django 4.1.7 on 2023-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_allergies_alter_patient_diseases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='link_key',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Klucz łączenia profilu'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kontaktowy e-mail'),
        ),
    ]
