# Generated by Django 4.1.7 on 2023-05-12 13:50

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_link_key_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None, verbose_name='Alergie'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diseases',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None, verbose_name='Choroby'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medicine',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None, verbose_name='Przyjmowane leki'),
        ),
    ]
