# Generated by Django 4.1.7 on 2023-05-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_allergies_alter_patient_diseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='link_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='Klucz łączenia profilu'),
        ),
    ]
