# Generated by Django 4.1.7 on 2023-05-13 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0010_alter_patient_link_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None, verbose_name='Alergie'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diseases',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None, verbose_name='Choroby'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medicine',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None, verbose_name='Przyjmowane leki'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
