# Generated by Django 4.1.7 on 2023-05-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patient_allergies_alter_patient_diseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/', verbose_name='Zdjęcie'),
        ),
    ]
