export const DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST";
export const DOCTOR_LIST_SUCCESS = "DOCTOR_LIST_SUCCESS";
export const DOCTOR_LIST_FAIL = "DOCTOR_LIST_FAIL";
export const DOCTOR_LIST_RESET = "DOCTOR_LIST_RESET";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";
export const DOCTOR_DETAILS_RESET = "DOCTOR_DETAILS_RESET";

export const SPECIALIZATION_LIST_REQUEST = "SPECIALIZATION_LIST_REQUEST";
export const SPECIALIZATION_LIST_SUCCESS = "SPECIALIZATION_LIST_SUCCESS";
export const SPECIALIZATION_LIST_FAIL = "SPECIALIZATION_LIST_FAIL";
export const SPECIALIZATION_LIST_RESET = "SPECIALIZATION_LIST_RESET";
