export const PATIENT_LIST_REQUEST = 'PATIENT_LIST_REQUEST';
export const PATIENT_LIST_SUCCESS = 'PATIENT_LIST_SUCCESS';
export const PATIENT_LIST_FAIL = 'PATIENT_LIST_FAIL';
export const PATIENT_LIST_RESET = 'PATIENT_LIST_RESET';

export const PATIENT_DETAILS_REQUEST = 'PATIENT_DETAILS_REQUEST';
export const PATIENT_DETAILS_SUCCESS = 'PATIENT_DETAILS_SUCCESS';
export const PATIENT_DETAILS_FAIL = 'PATIENT_DETAILS_FAIL';
export const PATIENT_DETAILS_RESET = 'PATIENT_DETAILS_RESET';
