export const SLOT_LIST_REQUEST = "SLOT_LIST_REQUEST";
export const SLOT_LIST_SUCCESS = "SLOT_LIST_SUCCESS";
export const SLOT_LIST_FAIL = "SLOT_LIST_FAIL";
export const SLOT_LIST_RESET = "SLOT_LIST_RESET";
