export const SLOT_LIST_REQUEST = "SLOT_LIST_REQUEST";
export const SLOT_LIST_SUCCESS = "SLOT_LIST_SUCCESS";
export const SLOT_LIST_FAIL = "SLOT_LIST_FAIL";
export const SLOT_LIST_RESET = "SLOT_LIST_RESET";

export const PATIENT_STATS_REQUEST = "PATIENT_STATS_REQUEST";
export const PATIENT_STATS_SUCCESS = "PATIENT_STATS_SUCCESS";
export const PATIENT_STATS_FAIL = "PATIENT_STATS_FAIL";
export const PATIENT_STATS_RESET = "PATIENT_STATS_RESET";

export const APPOINTMENT_STATS_REQUEST = "APPOINTMENT_STATS_REQUEST";
export const APPOINTMENT_STATS_SUCCESS = "APPOINTMENT_STATS_SUCCESS";
export const APPOINTMENT_STATS_FAIL = "APPOINTMENT_STATS_FAIL";
export const APPOINTMENT_STATS_RESET = "APPOINTMENT_STATS_RESET";
