# Generated by Django 4.1.7 on 2023-04-29 19:50

import apps.employees.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('gender', models.CharField(choices=[('Mężczyzna', 'Mężczyzna'), ('Kobieta', 'Kobieta'), ('Osoba niebinarna', 'Osoba niebinarna')], max_length=50, verbose_name='Płeć')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Recepcjonista',
                'verbose_name_plural': 'Recepcjoniści',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('fem_name', models.CharField(max_length=100, verbose_name='Feminatyw')),
            ],
            options={
                'verbose_name': 'Specjalizacja',
                'verbose_name_plural': 'Specjalizacje',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Początek tygodnia')),
                ('end_date', models.DateField(verbose_name='Koniec tygodnia')),
                ('monday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Poniedziałek')),
                ('tuesday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Wtorek')),
                ('wednesday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Środa')),
                ('thursday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Czwartek')),
                ('friday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Piątek')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='employees.doctor', verbose_name='Lekarz')),
            ],
            options={
                'verbose_name': 'Grafik lekarza',
                'verbose_name_plural': 'Grafik lekarzy',
                'ordering': ['id'],
            },
        ),
    ]
