# Generated by Django 4.1.7 on 2023-04-29 22:02

import apps.employees.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Początek tygodnia')),
                ('end_date', models.DateField(verbose_name='Koniec tygodnia')),
                ('monday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Poniedziałek')),
                ('tuesday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Wtorek')),
                ('wednesday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Środa')),
                ('thursday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Czwartek')),
                ('friday', apps.employees.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('09:00', '9:00'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30')], max_length=5), blank=True, null=True, size=None, verbose_name='Piątek')),
            ],
            options={
                'verbose_name': 'Grafik lekarza',
                'verbose_name_plural': 'Grafik lekarzy',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(to='employees.specialization', verbose_name='Specjalizacje'),
        ),
        migrations.DeleteModel(
            name='WeeklyPlan',
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='employees.doctor', verbose_name='Lekarz'),
        ),
    ]
