# Generated by Django 4.1.7 on 2023-04-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_schedule_alter_doctor_specializations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Koniec tygodnia'),
        ),
    ]
