# Generated by Django 4.1.7 on 2023-05-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_doctor_image_alter_receptionist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receptionists', verbose_name='Zdjęcie'),
        ),
    ]
