# Generated by Django 4.1.7 on 2023-05-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_doctor_image_alter_receptionist_image'),
        ('employees', '0012_alter_schedule_friday_alter_schedule_monday_and_more'),
    ]

    operations = [
    ]
